<?php

/**
 * Searchable pages for global search (Cmd+K).
 * Synced to Meilisearch via SearchService::syncPagesToIndex().
 * Add new pages here and run: php artisan search:reindex pages
 *
 * @see docs/ai/recipes/add-searchable-page.md
 */
return [
    // User pages (all users)
    [
        'id' => 'dashboard',
        'title' => 'Dashboard',
        'url' => '/dashboard',
        'admin_only' => false,
        'content' => 'home overview widgets statistics',
    ],
    [
        'id' => 'notifications',
        'title' => 'Notifications',
        'url' => '/notifications',
        'admin_only' => false,
        'content' => 'alerts messages notifications',
    ],
    [
        'id' => 'user-preferences',
        'title' => 'User Preferences',
        'url' => '/user/preferences',
        'admin_only' => false,
        'content' => 'settings profile preferences',
    ],
    [
        'id' => 'user-profile',
        'title' => 'User Profile',
        'url' => '/user/profile',
        'admin_only' => false,
        'content' => 'account avatar profile',
    ],
    [
        'id' => 'user-security',
        'title' => 'User Security',
        'subtitle' => 'Password, 2FA, passkeys, connected accounts',
        'url' => '/user/security',
        'admin_only' => false,
        'content' => 'password 2fa two-factor mfa passkeys sso connected accounts security',
    ],
    // Configuration pages (admin only)
    [
        'id' => 'config-system',
        'title' => 'Configuration > System',
        'subtitle' => 'Application-wide settings',
        'url' => '/configuration/system',
        'admin_only' => true,
        'content' => 'app general system settings',
    ],
    [
        'id' => 'config-branding',
        'title' => 'Configuration > Theme & Branding',
        'subtitle' => 'Visual customization',
        'url' => '/configuration/branding',
        'admin_only' => true,
        'content' => 'theme palette logo branding visual',
    ],
    [
        'id' => 'config-users',
        'title' => 'Configuration > Users',
        'subtitle' => 'Manage application users',
        'url' => '/configuration/users',
        'admin_only' => true,
        'content' => 'manage users admin user list',
    ],
    [
        'id' => 'config-groups',
        'title' => 'Configuration > Groups',
        'subtitle' => 'User groups and permissions',
        'url' => '/configuration/groups',
        'admin_only' => true,
        'content' => 'groups permissions roles members',
    ],
    [
        'id' => 'config-security',
        'title' => 'Configuration > Security',
        'subtitle' => 'Auth and security settings',
        'url' => '/configuration/security',
        'admin_only' => true,
        'content' => 'auth 2fa password reset TOTP email verification',
    ],
    [
        'id' => 'config-sso',
        'title' => 'Configuration > SSO',
        'subtitle' => 'Single sign-on providers',
        'url' => '/configuration/sso',
        'admin_only' => true,
        'content' => 'oauth google github gitlab microsoft azure ad apple discord OIDC SAML login',
    ],
    [
        'id' => 'config-api',
        'title' => 'Configuration > API & Webhooks',
        'subtitle' => 'API tokens and webhooks',
        'url' => '/configuration/api',
        'admin_only' => true,
        'content' => 'tokens webhooks API',
    ],
    [
        'id' => 'config-notifications',
        'title' => 'Configuration > Notifications',
        'subtitle' => 'Configure notification channels',
        'url' => '/configuration/notifications',
        'admin_only' => true,
        'content' => 'channels telegram discord slack signal twilio vonage SNS webpush FCM ntfy matrix',
    ],
    [
        'id' => 'config-email',
        'title' => 'Configuration > Email',
        'subtitle' => 'Email delivery configuration',
        'url' => '/configuration/email',
        'admin_only' => true,
        'content' => 'smtp mailgun sendgrid AWS SES postmark TLS encryption mail',
    ],
    [
        'id' => 'config-email-templates',
        'title' => 'Configuration > Email Templates',
        'subtitle' => 'Customize system emails',
        'url' => '/configuration/email-templates',
        'admin_only' => true,
        'content' => 'templates email subject body',
    ],
    [
        'id' => 'config-notification-templates',
        'title' => 'Configuration > Notification Templates',
        'subtitle' => 'Per-type push, in-app, chat templates',
        'url' => '/configuration/notification-templates',
        'admin_only' => true,
        'content' => 'notification templates push inapp chat per-type',
    ],
    [
        'id' => 'config-ai',
        'title' => 'Configuration > AI / LLM',
        'subtitle' => 'LLM providers and models',
        'url' => '/configuration/ai',
        'admin_only' => true,
        'content' => 'Claude Anthropic OpenAI GPT ChatGPT Google Gemini Vertex AI AWS Amazon Bedrock Ollama local models Azure OpenAI Groq Mistral Llama API key model selection council mode multi-provider primary fallback timeout',
    ],
    [
        'id' => 'config-storage',
        'title' => 'Configuration > Storage',
        'subtitle' => 'File storage configuration',
        'url' => '/configuration/storage',
        'admin_only' => true,
        'content' => 'S3 AWS Amazon bucket local disk filesystem upload size limit file types allowed extensions region endpoint credentials',
    ],
    [
        'id' => 'config-search',
        'title' => 'Configuration > Search',
        'subtitle' => 'Manage search indexes',
        'url' => '/configuration/search',
        'admin_only' => true,
        'content' => 'meilisearch index reindex search',
    ],
    [
        'id' => 'config-audit',
        'title' => 'Configuration > Audit Log',
        'subtitle' => 'View system activity logs',
        'url' => '/configuration/audit',
        'admin_only' => true,
        'content' => 'logs activity audit',
    ],
    [
        'id' => 'config-logs',
        'title' => 'Configuration > Application Logs',
        'subtitle' => 'Real-time console log viewer',
        'url' => '/configuration/logs',
        'admin_only' => true,
        'content' => 'console log viewer',
    ],
    [
        'id' => 'config-access-logs',
        'title' => 'Configuration > Access Logs (HIPAA)',
        'subtitle' => 'PHI access audit trail',
        'url' => '/configuration/access-logs',
        'admin_only' => true,
        'content' => 'hipaa phi access logs',
    ],
    [
        'id' => 'config-log-retention',
        'title' => 'Configuration > Log retention',
        'subtitle' => 'Retention and cleanup config',
        'url' => '/configuration/log-retention',
        'admin_only' => true,
        'content' => 'retention cleanup logs',
    ],
    [
        'id' => 'config-jobs',
        'title' => 'Configuration > Jobs',
        'subtitle' => 'Monitor scheduled jobs',
        'url' => '/configuration/jobs',
        'admin_only' => true,
        'content' => 'scheduled queue tasks jobs',
    ],
    [
        'id' => 'config-backup',
        'title' => 'Configuration > Backup & Restore',
        'subtitle' => 'Manage system backups',
        'url' => '/configuration/backup',
        'admin_only' => true,
        'content' => 'restore export backup S3 SFTP Google Drive encryption retention schedule',
    ],
    // Help articles (user-visible)
    [
        'id' => 'help-welcome',
        'title' => 'Help: Welcome to Sourdough',
        'subtitle' => 'Help article',
        'url' => 'help:welcome',
        'admin_only' => false,
        'content' => 'getting started overview introduction help guide features authentication',
    ],
    [
        'id' => 'help-navigation',
        'title' => 'Help: Navigating the App',
        'subtitle' => 'Help article',
        'url' => 'help:navigation',
        'admin_only' => false,
        'content' => 'menu sidebar navigate dashboard profile keyboard shortcuts',
    ],
    [
        'id' => 'help-search',
        'title' => 'Help: Using Search',
        'subtitle' => 'Help article',
        'url' => 'help:search',
        'admin_only' => false,
        'content' => 'search find filter cmd+k ctrl+k help articles',
    ],
    [
        'id' => 'help-theme-appearance',
        'title' => 'Help: Theme & Appearance',
        'subtitle' => 'Help article',
        'url' => 'help:theme-appearance',
        'admin_only' => false,
        'content' => 'theme dark light appearance customization preferences',
    ],
    [
        'id' => 'help-profile',
        'title' => 'Help: Managing Your Profile',
        'subtitle' => 'Help article',
        'url' => 'help:profile',
        'admin_only' => false,
        'content' => 'profile account avatar display name email settings',
    ],
    [
        'id' => 'help-password',
        'title' => 'Help: Changing Your Password',
        'subtitle' => 'Help article',
        'url' => 'help:password',
        'admin_only' => false,
        'content' => 'password security change reset requirements',
    ],
    [
        'id' => 'help-two-factor',
        'title' => 'Help: Two-Factor Authentication',
        'subtitle' => 'Help article',
        'url' => 'help:two-factor',
        'admin_only' => false,
        'content' => '2fa two-factor authenticator TOTP recovery codes security',
    ],
    [
        'id' => 'help-passkeys',
        'title' => 'Help: Using Passkeys',
        'subtitle' => 'Help article',
        'url' => 'help:passkeys',
        'admin_only' => false,
        'content' => 'passkey webauthn biometric fingerprint face sign in',
    ],
    [
        'id' => 'help-sessions',
        'title' => 'Help: Managing Sessions',
        'subtitle' => 'Help article',
        'url' => 'help:sessions',
        'admin_only' => false,
        'content' => 'session devices logout revoke active sessions',
    ],
    [
        'id' => 'help-notification-settings',
        'title' => 'Help: Notification Settings',
        'subtitle' => 'Help article',
        'url' => 'help:notification-settings',
        'admin_only' => false,
        'content' => 'notifications alerts preferences in-app email push',
    ],
    // Help articles (admin-only)
    [
        'id' => 'help-admin-overview',
        'title' => 'Help: Administration Overview',
        'subtitle' => 'Help article',
        'url' => 'help:admin-overview',
        'admin_only' => true,
        'content' => 'admin settings configuration user management audit logs',
    ],
    [
        'id' => 'help-user-management',
        'title' => 'Help: User Management',
        'subtitle' => 'Help article',
        'url' => 'help:user-management',
        'admin_only' => true,
        'content' => 'users admin accounts roles disable delete manage',
    ],
    [
        'id' => 'help-security-settings',
        'title' => 'Help: Security Configuration',
        'subtitle' => 'Help article',
        'url' => 'help:security-settings',
        'admin_only' => true,
        'content' => 'security policy 2fa password session SSO admin',
    ],
    [
        'id' => 'help-backup-settings',
        'title' => 'Help: Backup Configuration',
        'subtitle' => 'Help article',
        'url' => 'help:backup-settings',
        'admin_only' => true,
        'content' => 'backup restore admin data automatic manual',
    ],
    [
        'id' => 'help-branding',
        'title' => 'Help: Branding & Customization',
        'subtitle' => 'Help article',
        'url' => 'help:branding',
        'admin_only' => true,
        'content' => 'branding logo colors theme visual app name',
    ],
    [
        'id' => 'help-email-configuration',
        'title' => 'Help: Email Configuration',
        'subtitle' => 'Help article',
        'url' => 'help:email-configuration',
        'admin_only' => true,
        'content' => 'email smtp mailgun sendgrid AWS SES postmark delivery',
    ],
    [
        'id' => 'help-email-templates',
        'title' => 'Help: Email Templates',
        'subtitle' => 'Help article',
        'url' => 'help:email-templates',
        'admin_only' => true,
        'content' => 'email templates variables customize subject body',
    ],
    [
        'id' => 'help-sso-configuration',
        'title' => 'Help: SSO Configuration',
        'subtitle' => 'Help article',
        'url' => 'help:sso-configuration',
        'admin_only' => true,
        'content' => 'sso oauth google github single sign-on providers linking',
    ],
    [
        'id' => 'help-ai-llm-settings',
        'title' => 'Help: AI / LLM Settings',
        'subtitle' => 'Help article',
        'url' => 'help:ai-llm-settings',
        'admin_only' => true,
        'content' => 'ai llm openai anthropic claude models providers',
    ],
    [
        'id' => 'help-search-config',
        'title' => 'Help: Search Configuration',
        'subtitle' => 'Help article',
        'url' => 'help:search-config',
        'admin_only' => true,
        'content' => 'search meilisearch indexing reindex admin troubleshooting',
    ],
];
