<?php

/**
 * Searchable pages for global search (Cmd+K).
 * Synced to Meilisearch via SearchService::syncPagesToIndex().
 * Add new pages here and run: php artisan search:reindex pages
 *
 * @see docs/ai/recipes/add-searchable-page.md
 */
return [
    // User pages (all users)
    [
        'id' => 'dashboard',
        'title' => 'Dashboard',
        'url' => '/dashboard',
        'admin_only' => false,
        'content' => 'home overview widgets statistics',
    ],
    [
        'id' => 'notifications',
        'title' => 'Notifications',
        'url' => '/notifications',
        'admin_only' => false,
        'content' => 'alerts messages notifications',
    ],
    [
        'id' => 'user-preferences',
        'title' => 'User Preferences',
        'url' => '/user/preferences',
        'admin_only' => false,
        'content' => 'settings profile preferences',
    ],
    [
        'id' => 'user-profile',
        'title' => 'User Profile',
        'url' => '/user/profile',
        'admin_only' => false,
        'content' => 'account avatar profile',
    ],
    [
        'id' => 'user-security',
        'title' => 'User Security',
        'url' => '/user/security',
        'admin_only' => false,
        'content' => 'password 2fa two-factor security',
    ],
    // Configuration pages (admin only)
    [
        'id' => 'config-system',
        'title' => 'Configuration > System',
        'subtitle' => 'Application-wide settings',
        'url' => '/configuration/system',
        'admin_only' => true,
        'content' => 'app general system settings',
    ],
    [
        'id' => 'config-branding',
        'title' => 'Configuration > Theme & Branding',
        'subtitle' => 'Visual customization',
        'url' => '/configuration/branding',
        'admin_only' => true,
        'content' => 'theme palette logo branding visual',
    ],
    [
        'id' => 'config-users',
        'title' => 'Configuration > Users',
        'subtitle' => 'Manage application users',
        'url' => '/configuration/users',
        'admin_only' => true,
        'content' => 'manage users admin user list',
    ],
    [
        'id' => 'config-groups',
        'title' => 'Configuration > Groups',
        'subtitle' => 'User groups and permissions',
        'url' => '/configuration/groups',
        'admin_only' => true,
        'content' => 'groups permissions roles members',
    ],
    [
        'id' => 'config-security',
        'title' => 'Configuration > Security',
        'subtitle' => 'Auth and security settings',
        'url' => '/configuration/security',
        'admin_only' => true,
        'content' => 'auth 2fa password reset TOTP email verification',
    ],
    [
        'id' => 'config-sso',
        'title' => 'Configuration > SSO',
        'subtitle' => 'Single sign-on providers',
        'url' => '/configuration/sso',
        'admin_only' => true,
        'content' => 'oauth google github gitlab microsoft azure ad apple discord OIDC SAML login',
    ],
    [
        'id' => 'config-api',
        'title' => 'Configuration > API & Webhooks',
        'subtitle' => 'API tokens and webhooks',
        'url' => '/configuration/api',
        'admin_only' => true,
        'content' => 'tokens webhooks API',
    ],
    [
        'id' => 'config-notifications',
        'title' => 'Configuration > Notifications',
        'subtitle' => 'Configure notification channels',
        'url' => '/configuration/notifications',
        'admin_only' => true,
        'content' => 'channels telegram discord slack signal twilio vonage SNS webpush FCM ntfy matrix',
    ],
    [
        'id' => 'config-email',
        'title' => 'Configuration > Email',
        'subtitle' => 'Email delivery configuration',
        'url' => '/configuration/email',
        'admin_only' => true,
        'content' => 'smtp mailgun sendgrid AWS SES postmark TLS encryption mail',
    ],
    [
        'id' => 'config-email-templates',
        'title' => 'Configuration > Email Templates',
        'subtitle' => 'Customize system emails',
        'url' => '/configuration/email-templates',
        'admin_only' => true,
        'content' => 'templates email subject body',
    ],
    [
        'id' => 'config-notification-templates',
        'title' => 'Configuration > Notification Templates',
        'subtitle' => 'Per-type push, in-app, chat templates',
        'url' => '/configuration/notification-templates',
        'admin_only' => true,
        'content' => 'notification templates push inapp chat per-type',
    ],
    [
        'id' => 'config-ai',
        'title' => 'Configuration > AI / LLM',
        'subtitle' => 'LLM providers and models',
        'url' => '/configuration/ai',
        'admin_only' => true,
        'content' => 'Claude Anthropic OpenAI GPT ChatGPT Google Gemini Vertex AI AWS Amazon Bedrock Ollama local models Azure OpenAI Groq Mistral Llama API key model selection council mode multi-provider primary fallback timeout',
    ],
    [
        'id' => 'config-storage',
        'title' => 'Configuration > Storage',
        'subtitle' => 'File storage configuration',
        'url' => '/configuration/storage',
        'admin_only' => true,
        'content' => 'S3 AWS Amazon bucket local disk filesystem upload size limit file types allowed extensions region endpoint credentials',
    ],
    [
        'id' => 'config-search',
        'title' => 'Configuration > Search',
        'subtitle' => 'Manage search indexes',
        'url' => '/configuration/search',
        'admin_only' => true,
        'content' => 'meilisearch index reindex search',
    ],
    [
        'id' => 'config-audit',
        'title' => 'Configuration > Audit Log',
        'subtitle' => 'View system activity logs',
        'url' => '/configuration/audit',
        'admin_only' => true,
        'content' => 'logs activity audit',
    ],
    [
        'id' => 'config-logs',
        'title' => 'Configuration > Application Logs',
        'subtitle' => 'Real-time console log viewer',
        'url' => '/configuration/logs',
        'admin_only' => true,
        'content' => 'console log viewer',
    ],
    [
        'id' => 'config-access-logs',
        'title' => 'Configuration > Access Logs (HIPAA)',
        'subtitle' => 'PHI access audit trail',
        'url' => '/configuration/access-logs',
        'admin_only' => true,
        'content' => 'hipaa phi access logs',
    ],
    [
        'id' => 'config-log-retention',
        'title' => 'Configuration > Log retention',
        'subtitle' => 'Retention and cleanup config',
        'url' => '/configuration/log-retention',
        'admin_only' => true,
        'content' => 'retention cleanup logs',
    ],
    [
        'id' => 'config-jobs',
        'title' => 'Configuration > Jobs',
        'subtitle' => 'Monitor scheduled jobs',
        'url' => '/configuration/jobs',
        'admin_only' => true,
        'content' => 'scheduled queue tasks jobs',
    ],
    [
        'id' => 'config-backup',
        'title' => 'Configuration > Backup & Restore',
        'subtitle' => 'Manage system backups',
        'url' => '/configuration/backup',
        'admin_only' => true,
        'content' => 'restore export backup S3 SFTP Google Drive encryption retention schedule',
    ],
];
